config/routes.rb
CommunityBookshelf::Application.routes.draw do
  root 'home#index'

  get "home/index"
  get "home/settings"
  get "books/search"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
	def search
    render json: fetch_books(params)
  end

  def fetch_books(params)
    Rails.cache.fetch("books/#{params[:q]}/#{params[:p]}") { fetch_books!(params) }
  end

  def fetch_books!(params)
    GoogleBooks.search(params[:q], {:country => "fr", :count => 10, :page => params[:p].to_i, :api_key => ENV['API_KEY']}).to_json
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def settings
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<div ng-controller="BooksCtrl" ng-show="authenticated">
  <div id="my-library" ng-hide="search">
    <h2>
      My library
      <button type="button" class="btn btn-default btn-sm" ng-click="searchBook()">
        <span class="glyphicon glyphicon-plus"></span> Add book
      </button>
    </h2>

    <table class="table table-condensed">
      <thead>
        <th>Title</th>
        <th>Author</th>
        <th>Published</th>
        <th></th>
      </thead>
      <tr ng-repeat="book in myBooks | orderByPriority">
        <td>{{book.item.volumeInfo.title}}</td>
        <td>{{book.item.volumeInfo.authors.join(', ')}}</td>
        <td>{{book.item.volumeInfo.publishedDate}}</td>
        <td>
          <button type="button" class="btn btn-default btn-sm" ng-click="remove(book)">
            <span class="glyphicon glyphicon-minus"></span> Remove
          </button>
        </td>
      </tr>
    </table>
  </div>

  <div id="search-book" ng-show="search">
    <h2>Search a book</h2>
    <input type="text" ng-model="q"/>
    <button type="button" class="btn btn-default btn-sm" ng-click="submitSearch()">Search</button>
    <button type="button" class="btn btn-default btn-sm" ng-click="cancel()">Cancel</button>

    <div ng-show="availableBooks">
      <table class="table table-condensed">
        <thead>
          <th>Title</th>
          <th>Author</th>
          <th>Published</th>
          <th></th>
        </thead>
        <tr ng-repeat="book in availableBooks" ng-class="{'info': book.owned}">
          <td>{{book.item.volumeInfo.title}}</td>
          <td>{{book.item.volumeInfo.authors.join(', ')}}</td>
          <td>{{book.item.volumeInfo.publishedDate}}</td>
          <td><button type="button" class="btn btn-default btn-sm" ng-click="add(book)" ng-hide="book.owned">Add to library</button></td>
        </tr>
      </table>

      <button type="button" class="btn btn-default btn-sm" ng-click="previousPage()" ng-show"page !== 1">Previous</button>
      <span>{{page}}</span>
      <button type="button" class="btn btn-default btn-sm" ng-click="nextPage()">Next</button>
    </div>
  </div>
</div>

app/views/home/settings.html.erb
<div ng-controller="SettingsCtrl">
  <button type="button" class="btn btn-default btn-sm" ng-click="setLocation('test')">
    <span class="glyphicon glyphicon-plus"></span> Set location
  </button>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html ng-app="app">
<head>
  <title>Community Bookshelf</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="panel panel-default">
  <div class="panel-heading">
    <div ng-controller="AuthenticationCtrl">
      <button type="submit" ng-click="login()" ng-hide="authenticated">Login using Github</button>
      <span ng-show="authenticated">Hello {{user.name}}</span>
    </div>

    <div class="container">
      <div class="navbar-header">
        <button data-target=".bs-navbar-collapse" data-toggle="collapse" type="button" class="navbar-toggle">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="<%= home_index_path =%>">Home</a>
      </div>
      <nav role="navigation" class="collapse navbar-collapse bs-navbar-collapse">
        <ul class="nav navbar-nav">
          <li>
            <a href="<%= home_settings_path =%>">Settings</a>
          </li>
        </ul>
      </nav>
    </div>
  </div>
  <div class="panel-body">
    <%= yield %>
  </div>
</div>

</body>
</html>